### ISSUE TITLE
Landscape Orientation

### ISSUE THREAD

**Issue by dhlogan** [klimeryk/recalendar.js#102] opened 2023-10-11 14:12 UTC
I use my Remarkable in Landscape mode as it fits perfectly on my desk between me and my keyboard. I've grown used to the amount of screen space that I have in the Landscape orientation. Any chance you'd be able to add support for Landscape mode?

**Comment by klimeryk** [comment] 2023-10-24 22:39
Marking as duplicate of #70 🙇

**Closed by klimeryk** 2023-10-24 22:39 UTC
